const $=id=>document.getElementById(id);
const api=async(path,opts)=>{try{const r=await fetch(path,opts);if(!r.ok)throw Error(r.status);return await r.json()}catch(e){return null}};
const demoTracks={timestamp:new Date().toISOString(),mode:'DEMO FALLBACK',aircraft:[{id:'AEG-DEMO-01',callsign:'AEGIS01',type:'aircraft',lat:41.01,lon:28.97,altitude_ft:31000,speed_kt:430,heading:92,source:'demo'}],vessels:[{id:'SEA-DEMO-01',name:'AEGIS MARITIME',type:'vessel',lat:40.98,lon:29.04,speed_kt:12,heading:180,mmsi:'demo',source:'demo'}]};
let latestTracks=demoTracks, globe={yaw:0.35,pitch:0.12,zoom:1,drag:false,x:0,lastX:0,lastY:0}, selectedTrack=null;
function clock(){$('clock').textContent=new Date().toISOString().slice(11,19)+' UTC'}setInterval(clock,1000);clock();
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.section').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active');requestAnimationFrame(drawAllMaps)});
function metric(id,val){if($(id))$(id).textContent=val}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function project(lat,lon,w,h){const p=globe.pitch, y0=Math.sin((lat*Math.PI/180))*Math.cos(p)-Math.cos((lat*Math.PI/180))*Math.sin(p);const z=Math.sin((lat*Math.PI/180))*Math.sin(p)+Math.cos((lat*Math.PI/180))*Math.cos(p)*Math.cos((lon*Math.PI/180)-globe.yaw);const x=Math.cos(lat*Math.PI/180)*Math.sin((lon*Math.PI/180)-globe.yaw);const visible=z>-.02;const scale=Math.min(w,h)*.34*globe.zoom;return {x:w/2+x*scale,y:h/2-y0*scale,z,visible,scale}}
function drawGlobe(canvas,tracks){if(!canvas)return;const r=canvas.getBoundingClientRect(),d=devicePixelRatio||1,w=Math.max(1,r.width),h=Math.max(1,r.height);canvas.width=w*d;canvas.height=h*d;const c=canvas.getContext('2d');c.setTransform(d,0,0,d,0,0);c.clearRect(0,0,w,h);const R=Math.min(w,h)*.34*globe.zoom;
 const g=c.createRadialGradient(w*.43,h*.38,R*.08,w*.5,h*.5,R*1.18);g.addColorStop(0,'#173d26');g.addColorStop(.55,'#0a2115');g.addColorStop(1,'#010604');c.fillStyle=g;c.beginPath();c.arc(w/2,h/2,R,0,Math.PI*2);c.fill();
 c.save();c.beginPath();c.arc(w/2,h/2,R,0,Math.PI*2);c.clip();c.strokeStyle='rgba(84,231,255,.16)';c.lineWidth=1;
 for(let lon=-180;lon<180;lon+=20){c.beginPath();for(let lat=-90;lat<=90;lat+=3){const p=project(lat,lon,w,h);if(lat===-90)c.moveTo(p.x,p.y);else c.lineTo(p.x,p.y)}c.stroke()}
 for(let lat=-80;lat<=80;lat+=20){c.beginPath();for(let lon=-180;lon<=180;lon+=3){const p=project(lat,lon,w,h);if(lon===-180)c.moveTo(p.x,p.y);else c.lineTo(p.x,p.y)}c.stroke()}
 c.strokeStyle='rgba(99,255,155,.28)';c.lineWidth=1.2;c.beginPath();c.arc(w/2,h/2,R,0,Math.PI*2);c.stroke();
 // stylized continental masses: geographic context without external map dependency
 c.fillStyle='rgba(99,255,155,.10)';const land=[[[-10,35],[5,35],[22,45],[35,55],[55,55],[70,45],[90,30],[120,20],[145,35],[150,55],[120,65],[75,62],[40,58],[15,55],[-10,48]],[[-80,10],[-65,25],[-45,15],[-35,-5],[-50,-30],[-70,-50],[-80,-20]],[[-20,-35],[5,-35],[25,-15],[40,-5],[30,20],[10,15],[-5,5]]];land.forEach(poly=>{c.beginPath();poly.forEach((q,i)=>{const p=project(q[1],q[0],w,h);i?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y)});c.closePath();c.fill()});
 c.restore();
 const all=[...tracks.aircraft,...tracks.vessels];all.forEach(t=>{const p=project(Number(t.lat),Number(t.lon),w,h);if(!p.visible)return;const air=t.type==='aircraft';const color=air?'#54e7ff':'#ffc65c';const alt=Math.max(5,Math.min(110,(Number(t.altitude_ft)||50)/700));c.save();c.globalAlpha=.55;c.strokeStyle=color;c.lineWidth=1;c.beginPath();c.moveTo(p.x,p.y);c.lineTo(p.x,p.y-alt);c.stroke();c.globalAlpha=.16;c.beginPath();c.arc(p.x,p.y,10,0,Math.PI*2);c.stroke();c.globalAlpha=1;c.fillStyle=color;c.shadowColor=color;c.shadowBlur=12;c.beginPath();c.arc(p.x,p.y-alt,air?4:3,0,Math.PI*2);c.fill();c.shadowBlur=0;c.fillStyle='#b9d8c8';c.font='8px ui-monospace';c.fillText((t.callsign||t.name||t.id||'TRACK').slice(0,18),p.x+7,p.y-alt-5);c.restore()});
 if(selectedTrack){const p=project(Number(selectedTrack.lat),Number(selectedTrack.lon),w,h);if(p.visible){c.strokeStyle='#63ff9b';c.lineWidth=2;c.beginPath();c.arc(p.x,p.y,16,0,Math.PI*2);c.stroke()}}
 const sweep=(Date.now()/1000)%8/8*Math.PI*2;c.save();c.translate(w/2,h/2);c.rotate(sweep);c.strokeStyle='rgba(99,255,155,.25)';c.lineWidth=2;c.beginPath();c.moveTo(0,0);c.lineTo(R,0);c.stroke();c.restore();
}
function drawRadar(canvas,tracks){if(!canvas)return;const r=canvas.getBoundingClientRect(),d=devicePixelRatio||1,w=r.width,h=r.height;canvas.width=w*d;canvas.height=h*d;const c=canvas.getContext('2d');c.setTransform(d,0,0,d,0,0);c.clearRect(0,0,w,h);const cx=w/2,cy=h/2,R=Math.min(w,h)*.38;c.strokeStyle='rgba(99,255,155,.22)';[.35,.6,.85,1].forEach(k=>{c.beginPath();c.arc(cx,cy,R*k,0,Math.PI*2);c.stroke()});c.beginPath();c.moveTo(cx-R,cy);c.lineTo(cx+R,cy);c.moveTo(cx,cy-R);c.lineTo(cx,cy+R);c.stroke();const sweep=(Date.now()/1000)%5/5*Math.PI*2;c.save();c.translate(cx,cy);c.rotate(sweep);const gr=c.createLinearGradient(0,0,R,0);gr.addColorStop(0,'rgba(99,255,155,.5)');gr.addColorStop(1,'transparent');c.strokeStyle=gr;c.beginPath();c.moveTo(0,0);c.lineTo(R,0);c.stroke();c.restore();[...tracks.aircraft,...tracks.vessels].slice(0,60).forEach((t,i)=>{const x=cx+((Number(t.lon)%20)/20)*R*.85,y=cy-((Number(t.lat)%20)/20)*R*.85;c.fillStyle=t.type==='aircraft'?'#54e7ff':'#ffc65c';c.shadowColor=c.fillStyle;c.shadowBlur=8;c.fillRect(x-2,y-2,4,4);c.shadowBlur=0})}
function drawAllMaps(){drawGlobe($('globeCanvas'),latestTracks);drawRadar($('radarCanvas'),latestTracks)}setInterval(drawAllMaps,80);
function bindGlobe(){const canvas=$('globeCanvas');if(!canvas)return;canvas.addEventListener('pointerdown',e=>{globe.drag=true;globe.x=e.clientX;globe.lastX=e.clientX;globe.lastY=e.clientY;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!globe.drag)return;globe.yaw+=(e.clientX-globe.lastX)*.008;globe.pitch=Math.max(-.9,Math.min(.9,globe.pitch+(e.clientY-globe.lastY)*.006));globe.lastX=e.clientX;globe.lastY=e.clientY});canvas.addEventListener('pointerup',()=>globe.drag=false);canvas.addEventListener('wheel',e=>{e.preventDefault();globe.zoom=Math.max(.72,Math.min(1.45,globe.zoom*(e.deltaY<0?1.08:.92)))},{passive:false});canvas.addEventListener('click',e=>{const r=canvas.getBoundingClientRect();let best=null,bd=20;[...latestTracks.aircraft,...latestTracks.vessels].forEach(t=>{const p=project(Number(t.lat),Number(t.lon),r.width,r.height);if(!p.visible)return;const d=Math.hypot(p.x-(e.clientX-r.left),p.y-(e.clientY-r.top));if(d<bd){bd=d;best=t}});selectedTrack=best;showTrackIntel(best)})}
function showTrackIntel(t){let box=$('trackIntel');if(!box)return;if(!t){box.innerHTML='<div class="sub">SELECT A TRACK ON THE GLOBE</div>';return}box.innerHTML=`<div class="intelHead"><b>${esc(t.callsign||t.name||t.id)}</b><span class="badge">${esc(t.type||'TRACK').toUpperCase()}</span></div><div class="intelGrid"><span>LAT</span><b>${Number(t.lat).toFixed(4)}</b><span>LON</span><b>${Number(t.lon).toFixed(4)}</b><span>ALT</span><b>${Number(t.altitude_ft||0).toLocaleString()} FT</b><span>SPEED</span><b>${t.speed_kt??0} KT</b><span>HEADING</span><b>${t.heading??0}°</b><span>SOURCE</span><b>${esc(t.source||'—')}</b></div>`}
function renderTracks(t){metric('airCount',t.aircraft.length);metric('seaCount',t.vessels.length);$('tracks').innerHTML=[...t.aircraft,...t.vessels].slice(0,100).map(x=>`<tr><td class="mono">${esc(x.id||'—')}</td><td>${esc(x.type||'—')}</td><td>${Number(x.lat).toFixed(3)}, ${Number(x.lon).toFixed(3)}</td><td>${x.speed_kt??0} kt</td><td>${x.heading??0}°</td><td>${esc(x.source||'—')}</td></tr>`).join('');$('airTable').innerHTML=t.aircraft.slice(0,100).map(x=>`<tr><td>${esc(x.callsign||'UNKNOWN')}</td><td>${Number(x.lat).toFixed(3)}, ${Number(x.lon).toFixed(3)}</td><td>${Number(x.altitude_ft||0).toLocaleString()} ft</td><td>${x.speed_kt??0} kt</td><td>${x.heading??0}°</td><td>${esc(x.source)}</td></tr>`).join('');$('seaTable').innerHTML=t.vessels.slice(0,100).map(x=>`<tr><td>${esc(x.name||'UNKNOWN')}</td><td>${Number(x.lat).toFixed(3)}, ${Number(x.lon).toFixed(3)}</td><td>${x.speed_kt??0} kt</td><td>${x.heading??0}°</td><td>${esc(x.mmsi||'—')}</td><td>${esc(x.source||'—')}</td></tr>`).join('');$('radarData').textContent=JSON.stringify({mode:t.mode,timestamp:t.timestamp,aircraft:t.aircraft.slice(0,8),vessels:t.vessels.slice(0,8)},null,2);latestTracks=t;drawAllMaps();}
function setScannerState(info){const text=info?.engine?.available?'CLAMAV + AEGIS':'AEGIS HEURISTIC';metric('scannerMini',text);$('scannerInfo').textContent=JSON.stringify(info||{mode:'backend unavailable',engines:['Aegis heuristic']},null,2)}
async function refresh(){
 const s=await api('/api/system');if(s){metric('cpu',Math.round(s.cpu.percent)+'%');metric('mem',Math.round(s.memory.percent)+'%');metric('disk',Math.round(s.disk.percent)+'%');$('cpuBar').style.width=s.cpu.percent+'%';$('memBar').style.width=s.memory.percent+'%';$('diskBar').style.width=s.disk.percent+'%';$('system').textContent=JSON.stringify(s,null,2);$('fullSystem').textContent=JSON.stringify(s,null,2)}else{$('system').textContent='STATIC DEMO MODE\nBackend API not reachable from this deployment.';$('fullSystem').textContent='STATIC DEMO MODE\nConnect the FastAPI backend for live host telemetry.'}
 const t=await api('/api/tracking')||demoTracks;renderTracks(t);
 const a=await api('/api/assessment');if(a){metric('risk',a.level||'LOW');$('riskScore').textContent='score '+(a.score??'—');$('signals').innerHTML=(a.signals||[]).map(x=>`<div class="event"><b class="${x.severity||'low'}">${x.severity||'LOW'}</b> ${esc(x.message||x)}</div>`).join('')||'<div class="ok">No elevated signals.</div>'}else{$('risk').textContent='LOCAL';$('riskScore').textContent='backend offline';$('signals').innerHTML='<div class="ok">Static interface online. Backend assessment unavailable.</div>'}
 const ev=await api('/api/events');if(ev)$('events').innerHTML=ev.slice(0,12).map(x=>`<div class="event"><b class="${x.severity||'low'}">${esc(x.severity||'LOW')}</b> ${esc(x.title)}<div class="sub">${esc(x.source||'system')} · ${esc(x.created_at||'')}</div></div>`).join('')||'<div class="sub">No events.</div>';
 const sec=await api('/api/security/status');if(sec)$('securityData').textContent=JSON.stringify(sec,null,2);
 const interfaces=await api('/api/interfaces');if(interfaces&&$('networkData'))$('networkData').textContent=JSON.stringify(interfaces,null,2);
 const integrity=await api('/api/integrity');if(integrity&&$('integrityData'))$('integrityData').textContent=JSON.stringify(integrity,null,2);
 const proc=await api('/api/processes');if(proc)$('processes').innerHTML=proc.slice(0,20).map(x=>`<tr><td>${x.pid}</td><td>${esc(x.name||'')}</td><td>${x.cpu_percent??0}</td><td>${x.memory_percent??0}</td></tr>`).join('');
 setScannerState(await api('/api/security/scanner')||await api('/api/malware/status'));
 const comms=await api('/api/comms/messages?room=command');if(comms)renderMessages(comms)
}
async function scanFile(){const path=$('scanPath').value.trim();if(!path){toast('Enter a local file path');return}const r=await api('/api/security/scan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path})});$('scanResult').textContent=JSON.stringify(r||{error:'Backend unavailable'},null,2);toast(r?'Scan complete':'Backend unavailable');refresh()}
async function sendMessage(){const sender=$('sender').value.trim()||'AEGIS-OPERATOR',message=$('message').value.trim();if(!message)return;const r=await api('/api/comms/messages',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({room:'command',sender,message})});if(r){$('message').value='';renderMessages(await api('/api/comms/messages?room=command')||[]);toast('Encrypted message stored')}else toast('Secure room backend unavailable')}
function renderMessages(list){$('messages').innerHTML=list.length?list.map(x=>`<div class="msg"><b>${esc(x.sender)}</b><div>${esc(x.message||'[encrypted payload]')}</div><div class="sub">${esc(x.created_at||'')}</div></div>`).join(''):'<div class="sub">SECURE ROOM READY — no messages.</div>'}
function toast(t){$('toast').textContent=t;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',2200)}
bindGlobe();refresh();setInterval(refresh,5000);