const $=id=>document.getElementById(id);
const api=async(path,opts)=>{try{const r=await fetch(path,opts);if(!r.ok)throw Error(r.status);return await r.json()}catch(e){return null}};
const demoTracks={timestamp:new Date().toISOString(),mode:'DEMO FALLBACK',aircraft:[{id:'AEG-DEMO-01',callsign:'AEGIS01',type:'aircraft',lat:41.01,lon:28.97,altitude_ft:31000,speed_kt:430,heading:92,source:'demo'}],vessels:[{id:'SEA-DEMO-01',name:'AEGIS MARITIME',type:'vessel',lat:40.98,lon:29.04,speed_kt:12,heading:180,mmsi:'demo',source:'demo'}]};
function clock(){$('clock').textContent=new Date().toISOString().slice(11,19)+' UTC'}setInterval(clock,1000);clock();
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.section').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active')});
function metric(id,val){if($(id))$(id).textContent=val}
function renderMap(t){const map=$('map');if(!map)return;map.querySelectorAll('.track').forEach(x=>x.remove());[...t.aircraft,...t.vessels].slice(0,80).forEach(x=>{const p=document.createElement('div');p.className='track '+(x.type==='vessel'?'sea':'air');p.style.left=(8+((Number(x.lon)+180)%360)/360*84)+'%';p.style.top=(8+(90-Number(x.lat))/180*84)+'%';p.innerHTML='<span>'+((x.callsign||x.name||x.id)||'TRACK')+'</span>';p.title=`${x.callsign||x.name||x.id} · ${x.lat}, ${x.lon}`;map.appendChild(p)})}
function renderTracks(t){metric('airCount',t.aircraft.length);metric('seaCount',t.vessels.length);$('tracks').innerHTML=[...t.aircraft,...t.vessels].slice(0,100).map(x=>`<tr><td class="mono">${x.id||'—'}</td><td>${x.type||'—'}</td><td>${Number(x.lat).toFixed(3)}, ${Number(x.lon).toFixed(3)}</td><td>${x.speed_kt??0} kt</td><td>${x.heading??0}°</td><td>${x.source||'—'}</td></tr>`).join('');$('airTable').innerHTML=t.aircraft.slice(0,100).map(x=>`<tr><td>${x.callsign||'UNKNOWN'}</td><td>${Number(x.lat).toFixed(3)}, ${Number(x.lon).toFixed(3)}</td><td>${Number(x.altitude_ft||0).toLocaleString()} ft</td><td>${x.speed_kt??0} kt</td><td>${x.heading??0}°</td><td>${x.source}</td></tr>`).join('');$('seaTable').innerHTML=t.vessels.slice(0,100).map(x=>`<tr><td>${x.name||'UNKNOWN'}</td><td>${Number(x.lat).toFixed(3)}, ${Number(x.lon).toFixed(3)}</td><td>${x.speed_kt??0} kt</td><td>${x.heading??0}°</td><td>${x.mmsi||'—'}</td><td>${x.source}</td></tr>`).join('');$('radarData').textContent=JSON.stringify({mode:t.mode,timestamp:t.timestamp,aircraft:t.aircraft.slice(0,8),vessels:t.vessels.slice(0,8)},null,2);renderMap(t)}
function setScannerState(info){const text=info?.engine?.available?'CLAMAV + AEGIS':'AEGIS HEURISTIC';metric('scannerMini',text);$('scannerInfo').textContent=JSON.stringify(info||{mode:'backend unavailable',engines:['Aegis heuristic']},null,2)}
async function refresh(){
 const s=await api('/api/system');
 if(s){metric('cpu',Math.round(s.cpu.percent)+'%');metric('mem',Math.round(s.memory.percent)+'%');metric('disk',Math.round(s.disk.percent)+'%');$('cpuBar').style.width=s.cpu.percent+'%';$('memBar').style.width=s.memory.percent+'%';$('diskBar').style.width=s.disk.percent+'%';$('system').textContent=JSON.stringify(s,null,2);$('fullSystem').textContent=JSON.stringify(s,null,2)}else{$('system').textContent='STATIC DEMO MODE\nBackend API not reachable from this deployment.';$('fullSystem').textContent='STATIC DEMO MODE\nConnect the FastAPI backend for live host telemetry.'}
 const t=await api('/api/tracking')||demoTracks;renderTracks(t);
 const a=await api('/api/assessment');if(a){metric('risk',a.level||'LOW');$('riskScore').textContent='score '+(a.score??'—');$('signals').innerHTML=(a.signals||[]).map(x=>`<div class="event"><b class="${x.severity||'low'}">${x.severity||'LOW'}</b> ${x.message||x}</div>`).join('')||'<div class="ok">No elevated signals.</div>'}else{$('risk').textContent='LOCAL';$('riskScore').textContent='backend offline';$('signals').innerHTML='<div class="ok">Static interface online. Backend assessment unavailable.</div>'}
 const ev=await api('/api/events');if(ev)$('events').innerHTML=ev.slice(0,12).map(x=>`<div class="event"><b class="${x.severity||'low'}">${x.severity||'LOW'}</b> ${x.title}<div class="sub">${x.source||'system'} · ${x.created_at||''}</div></div>`).join('')||'<div class="sub">No events.</div>';
 const sec=await api('/api/security/status');if(sec)$('securityData').textContent=JSON.stringify(sec,null,2);
 const proc=await api('/api/processes');if(proc)$('processes').innerHTML=proc.slice(0,20).map(x=>`<tr><td>${x.pid}</td><td>${x.name||''}</td><td>${x.cpu_percent??0}</td><td>${x.memory_percent??0}</td></tr>`).join('');
 setScannerState(await api('/api/security/scanner')||await api('/api/malware/status'));
 const comms=await api('/api/comms/messages?room=command');if(comms)renderMessages(comms)
}
async function scanFile(){const path=$('scanPath').value.trim();if(!path){toast('Enter a local file path');return}const r=await api('/api/security/scan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path})});$('scanResult').textContent=JSON.stringify(r||{error:'Backend unavailable'},null,2);toast(r?'Scan complete':'Backend unavailable');refresh()}
async function sendMessage(){const sender=$('sender').value.trim()||'AEGIS-OPERATOR',message=$('message').value.trim();if(!message)return;const r=await api('/api/comms/messages',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({room:'command',sender,message})});if(r){$('message').value='';renderMessages(await api('/api/comms/messages?room=command')||[]);toast('Encrypted message stored')}else toast('Secure room backend unavailable')}
function renderMessages(list){$('messages').innerHTML=list.length?list.map(x=>`<div class="msg"><b>${x.sender}</b><div>${x.message||'[encrypted payload]'}</div><div class="sub">${x.created_at||''}</div></div>`).join(''):'<div class="sub">SECURE ROOM READY — no messages.</div>'}
function toast(t){$('toast').textContent=t;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',2200)}
refresh();setInterval(refresh,5000);