const $=id=>document.getElementById(id);const api=async(path,opts)=>{try{const r=await fetch(path,opts);if(!r.ok)throw Error(r.status);return await r.json()}catch(e){return null}};
const demoTracks={timestamp:new Date().toISOString(),mode:'DEMO FALLBACK',aircraft:[{id:'AEG-DEMO-01',callsign:'AEGIS01',type:'aircraft',lat:41.01,lon:28.97,altitude_ft:31000,speed_kt:430,heading:92,source:'demo'}],vessels:[{id:'SEA-DEMO-01',name:'AEGIS MARITIME',type:'vessel',lat:40.98,lon:29.04,speed_kt:12,heading:180,mmsi:'demo',source:'demo'}]};
function clock(){$('clock').textContent=new Date().toISOString().slice(11,19)+' UTC'}setInterval(clock,1000);clock();
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.section').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active');if(b.dataset.tab==='radar')setTimeout(()=>drawRadarMini(lastTracks),50)});
function metric(id,val){if($(id))$(id).textContent=val}let lastTracks=demoTracks;
function latLonTo3D(lat,lon,rotY,tilt=0){const la=lat*Math.PI/180,lo=(lon+rotY)*Math.PI/180,x=Math.cos(la)*Math.sin(lo),z=Math.cos(la)*Math.cos(lo),y=Math.sin(la),yy=y*Math.cos(tilt)-z*Math.sin(tilt),zz=y*Math.sin(tilt)+z*Math.cos(tilt);return{x,y:yy,z:zz}}
function globeProject(p,w,h,r){return{x:w/2+p.x*r,y:h/2-p.y*r,visible:p.z>-.08}}
function drawGeoLine(c,pts,rot,tilt,r,w,h,color,width){let started=false;c.strokeStyle=color;c.lineWidth=width;c.beginPath();for(const g of pts){const p=latLonTo3D(g.lat,g.lon,rot,tilt),q=globeProject(p,w,h,r);if(!q.visible){started=false;continue}if(!started){c.moveTo(q.x,q.y);started=true}else c.lineTo(q.x,q.y)}c.stroke()}
const globeState={lon:0,tilt:.18,drag:false,x:0,y:0,zoom:1};
function drawGlobe(tracks){const canvas=$('globeCanvas');if(!canvas)return;const box=canvas.parentElement,d=devicePixelRatio||1,w=box.clientWidth,h=box.clientHeight;canvas.width=w*d;canvas.height=h*d;const c=canvas.getContext('2d');c.setTransform(d,0,0,d,0,0);c.clearRect(0,0,w,h);const r=Math.min(w,h)*.34*globeState.zoom,rot=globeState.lon,tilt=globeState.tilt;
const grad=c.createRadialGradient(w*.42,h*.38,r*.1,w*.5,h*.5,r*1.15);grad.addColorStop(0,'#163d25');grad.addColorStop(.55,'#082014');grad.addColorStop(1,'#020604');c.fillStyle=grad;c.beginPath();c.arc(w/2,h/2,r,0,Math.PI*2);c.fill();
for(let lat=-75;lat<=75;lat+=15)drawGeoLine(c,Array.from({length:181},(_,i)=>({lat,lon:-180+i*2})),rot,tilt,r,w,h,'#63ff9b28',1);for(let lon=-180;lon<180;lon+=15)drawGeoLine(c,Array.from({length:91},(_,i)=>({lat:-90+i*2,lon})),rot,tilt,r,w,h,'#63ff9b24',1);
const outlines=[[[41,29],[45,25],[48,31],[55,38],[51,50],[44,55],[36,50],[30,40],[25,35],[30,28],[41,29]],[[0,-60],[10,-55],[15,-45],[5,-35],[-10,-38],[-25,-50],[-5,-65],[0,-60]],[[25,-105],[45,-100],[55,-90],[50,-75],[35,-65],[20,-85],[25,-105]],[[35,100],[50,110],[55,135],[45,150],[25,140],[15,120],[35,100]]];outlines.forEach(o=>drawGeoLine(c,o,rot,tilt,r,w,h,'#8cffb047',1.5));
[...tracks.aircraft,...tracks.vessels].slice(0,120).forEach(x=>{const p=latLonTo3D(Number(x.lat),Number(x.lon),rot,tilt),q=globeProject(p,w,h,r);if(!q.visible)return;const color=x.type==='vessel'?'#ffc65c':'#54e7ff',rr=x.type==='vessel'?4:4.5;c.beginPath();c.fillStyle=color;c.shadowBlur=14;c.shadowColor=color;c.arc(q.x,q.y,rr,0,Math.PI*2);c.fill();c.shadowBlur=0;c.strokeStyle=color+'55';c.beginPath();c.arc(q.x,q.y,rr+7,0,Math.PI*2);c.stroke();c.fillStyle='#b8d9c8';c.font='8px ui-monospace';c.fillText((x.callsign||x.name||x.id||'TRACK').slice(0,16),q.x+9,q.y-7)});
c.strokeStyle='#63ff9b30';c.lineWidth=1;c.beginPath();c.arc(w/2,h/2,r+18,0,Math.PI*2);c.stroke();c.beginPath();c.arc(w/2,h/2,3+Math.sin(Date.now()/250)*1.5,0,Math.PI*2);c.fillStyle='#63ff9b';c.fill()}
function setupGlobe(){const canvas=$('globeCanvas');if(!canvas)return;canvas.addEventListener('pointerdown',e=>{globeState.drag=true;globeState.x=e.clientX;globeState.y=e.clientY;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!globeState.drag)return;globeState.lon+=(e.clientX-globeState.x)*.35;globeState.tilt=Math.max(-.65,Math.min(.65,globeState.tilt+(e.clientY-globeState.y)*.004));globeState.x=e.clientX;globeState.y=e.clientY;drawGlobe(lastTracks)});canvas.addEventListener('pointerup',()=>globeState.drag=false);canvas.addEventListener('wheel',e=>{e.preventDefault();globeState.zoom=Math.max(.75,Math.min(1.35,globeState.zoom-e.deltaY*.0007));drawGlobe(lastTracks)},{passive:false});requestAnimationFrame(animateGlobe)}
function animateGlobe(){if(!globeState.drag)globeState.lon+=.045;drawGlobe(lastTracks);requestAnimationFrame(animateGlobe)}
function drawRadarMini(t){const canvas=$('radarCanvas');if(!canvas)return;const box=canvas.parentElement,d=devicePixelRatio||1,w=box.clientWidth,h=box.clientHeight;canvas.width=w*d;canvas.height=h*d;const c=canvas.getContext('2d');c.setTransform(d,0,0,d,0,0);c.clearRect(0,0,w,h);const cx=w/2,cy=h/2,r=Math.min(w,h)*.38;c.strokeStyle='#63ff9b33';for(let i=1;i<=4;i++){c.beginPath();c.arc(cx,cy,r*i/4,0,Math.PI*2);c.stroke()}for(let a=0;a<Math.PI*2;a+=Math.PI/8){c.beginPath();c.moveTo(cx,cy);c.lineTo(cx+Math.cos(a)*r,cy+Math.sin(a)*r);c.stroke()}const sweep=Date.now()/1300,sx=cx+Math.cos(sweep)*r,sy=cy+Math.sin(sweep)*r;c.strokeStyle='#63ff9b99';c.beginPath();c.moveTo(cx,cy);c.lineTo(sx,sy);c.stroke();[...t.aircraft,...t.vessels].forEach(x=>{const px=cx+(Number(x.lon)%30)/30*r*.85,py=cy-(Number(x.lat)%30)/30*r*.85;c.fillStyle=x.type==='vessel'?'#ffc65c':'#54e7ff';c.shadowBlur=12;c.shadowColor=c.fillStyle;c.beginPath();c.arc(px,py,4,0,Math.PI*2);c.fill();c.shadowBlur=0})}
function renderMap(t){lastTracks=t;drawGlobe(t)}
function renderTracks(t){metric('airCount',t.aircraft.length);metric('seaCount',t.vessels.length);$('tracks').innerHTML=[...t.aircraft,...t.vessels].slice(0,100).map(x=>`<tr><td class="mono">${x.id||'—'}</td><td>${x.type||'—'}</td><td>${Number(x.lat).toFixed(3)}, ${Number(x.lon).toFixed(3)}</td><td>${x.speed_kt??0} kt</td><td>${x.heading??0}°</td><td>${x.source||'—'}</td></tr>`).join('');$('airTable').innerHTML=t.aircraft.slice(0,100).map(x=>`<tr><td>${x.callsign||'UNKNOWN'}</td><td>${Number(x.lat).toFixed(3)}, ${Number(x.lon).toFixed(3)}</td><td>${Number(x.altitude_ft||0).toLocaleString()} ft</td><td>${x.speed_kt??0} kt</td><td>${x.heading??0}°</td><td>${x.source}</td></tr>`).join('');$('seaTable').innerHTML=t.vessels.slice(0,100).map(x=>`<tr><td>${x.name||'UNKNOWN'}</td><td>${Number(x.lat).toFixed(3)}, ${Number(x.lon).toFixed(3)}</td><td>${x.speed_kt??0} kt</td><td>${x.heading??0}°</td><td>${x.mmsi||'—'}</td><td>${x.source}</td></tr>`).join('');$('radarData').textContent=JSON.stringify({mode:t.mode,timestamp:t.timestamp,aircraft:t.aircraft.slice(0,8),vessels:t.vessels.slice(0,8)},null,2);renderMap(t);drawRadarMini(t)}
function setScannerState(info){const text=info?.engine?.available?'CLAMAV + AEGIS':'AEGIS HEURISTIC';metric('scannerMini',text);$('scannerInfo').textContent=JSON.stringify(info||{mode:'backend unavailable',engines:['Aegis heuristic']},null,2)}
async function refresh(){const s=await api('/api/system');if(s){metric('cpu',Math.round(s.cpu.percent)+'%');metric('mem',Math.round(s.memory.percent)+'%');metric('disk',Math.round(s.disk.percent)+'%');$('cpuBar').style.width=s.cpu.percent+'%';$('memBar').style.width=s.memory.percent+'%';$('diskBar').style.width=s.disk.percent+'%';$('system').textContent=JSON.stringify(s,null,2);$('fullSystem').textContent=JSON.stringify(s,null,2)}else{$('system').textContent='STATIC DEMO MODE\nBackend API not reachable from this deployment.';$('fullSystem').textContent='STATIC DEMO MODE\nConnect the FastAPI backend for live host telemetry.'}const t=await api('/api/tracking')||demoTracks;renderTracks(t);const a=await api('/api/assessment');if(a){metric('risk',a.level||'LOW');$('riskScore').textContent='score '+(a.score??'—');$('signals').innerHTML=(a.signals||[]).map(x=>`<div class="event"><b class="${x.severity||'low'}">${x.severity||'LOW'}</b> ${x.message||x}</div>`).join('')||'<div class="ok">No elevated signals.</div>'}else{$('risk').textContent='LOCAL';$('riskScore').textContent='backend offline';$('signals').innerHTML='<div class="ok">Static interface online. Backend assessment unavailable.</div>'}const ev=await api('/api/events');if(ev)$('events').innerHTML=ev.slice(0,12).map(x=>`<div class="event"><b class="${x.severity||'low'}">${x.severity||'LOW'}</b> ${x.title}<div class="sub">${x.source||'system'} · ${x.created_at||''}</div></div>`).join('')||'<div class="sub">No events.</div>';const sec=await api('/api/security/status');if(sec)$('securityData').textContent=JSON.stringify(sec,null,2);const proc=await api('/api/processes');if(proc)$('processes').innerHTML=proc.slice(0,20).map(x=>`<tr><td>${x.pid}</td><td>${x.name||''}</td><td>${x.cpu_percent??0}</td><td>${x.memory_percent??0}</td></tr>`).join('');setScannerState(await api('/api/security/scanner')||await api('/api/malware/status'));const comms=await api('/api/comms/messages?room=command');if(comms)renderMessages(comms)}
async function scanFile(){const path=$('scanPath').value.trim();if(!path){toast('Enter a local file path');return}const r=await api('/api/security/scan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path})});$('scanResult').textContent=JSON.stringify(r||{error:'Backend unavailable'},null,2);toast(r?'Scan complete':'Backend unavailable');refresh()}
async function sendMessage(){const sender=$('sender').value.trim()||'AEGIS-OPERATOR',message=$('message').value.trim();if(!message)return;const r=await api('/api/comms/messages',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({room:'command',sender,message})});if(r){$('message').value='';renderMessages(await api('/api/comms/messages?room=command')||[]);toast('Encrypted message stored')}else toast('Secure room backend unavailable')}
function renderMessages(list){$('messages').innerHTML=list.length?list.map(x=>`<div class="msg"><b>${x.sender}</b><div>${x.message||'[encrypted payload]'}</div><div class="sub">${x.created_at||''}</div></div>`).join(''):'<div class="sub">SECURE ROOM READY — no messages.</div>'}
function toast(t){$('toast').textContent=t;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',2200)}
setupGlobe();refresh();setInterval(refresh,5000);